### PR TITLE
Make testParser public

### PR DESCRIPTION
**Pull request by data-man**

### CODE REVIEW

**Comment by Hejsil** [comment]
Hmm, not sure I would be happy making this awful function public. It needs a better API an cleaner implementation for that to happen. I might look into making a function called `expectResult` (following the `std.testing`) naming and having it have the following signature:
```
pub fn expectResult(comptime T: type, expect: Result(T), actual: Result(T)) void
```

**Comment by data-man** [comment]
> I might look into making a function called expectResult (following the std.testing naming) and having it have the following signature

Super!

------------
I'm working on Unicode matchers, so I need this function.
What do you prefer?

- Draft PR
- New issue with some ideas

**Comment by Hejsil** [comment]
I'm up for a draft PR if you already have some code to show :+1:

**Comment by data-man** [comment]
Maybe I'll first create an issue with different approaches?
If you don't mind. :)

**Comment by Hejsil** [comment]
Don't mind at all

**Pull request closed without merging**
