### PR TITLE
Track parser position for error reporting

### PR DESCRIPTION
**Pull request by joelreymont**
No span tracking is being done, just position tracking for error reporting.

### CODE REVIEW

**Comment by joelreymont** [comment]
Why do tests keep failing in CI?

**Comment by Hejsil** [comment]
> Why do tests keep failing in CI?

No idea. I'll take a proper look this weekend :pray:

**Comment by Hejsil** [comment]
> Why do tests keep failing in CI?

You have these lines:

```zig
var res: Res = undefined;
var pos: usize = 0;
res.ok.rest = str;
```

This is illegal behavior. You're initializing `Res` to `undefined` and then accessing through the union with `res.ok`. `res.ok` is not the active field. Nothing is the active field. The fix is this:

I don't see why you need to initialize a `Res` right here. Just keep track of `Res.Ok`

```
var res: Res.Ok = undefined;
var pos: usize = 0;
res.rest = str;
```

**Comment by joelreymont** [comment]
I wonder if this is a compiler regression because my 2 Macs have different versions of the Zig master and they haven't caught this.

**Comment by joelreymont** [comment]
Is anything else missing here?

Can you accept the PR?

**Comment by Hejsil** [comment]
> Is anything else missing here?
> 
> Can you accept the PR?

There are some changes I want to make, which have ended up taking a bit. Hopefully this will be merged in some modified form within this week

**Comment by joelreymont** [comment]
What changes are you planning?

**Comment by Hejsil** [comment]
My plan is to make `Result` this:

```zig
pub fn Result(comptime T: type) type {
    return struct {
        index: usize,
        value: union(enum) {
            ok: T,
            err,
        },

        pub fn ok(index: usize, value: T) @This() {
            return .{ .index = index, .value = .{ .ok = value } };
        }

        pub fn err(index: usize) @This() {
            return .{ .index = index, .value = .err };
        }
    };
}
```

Which results in a lot of small changes. There where also some bugs I'm ironing out which hopefully should yield even better error positions (in the json example, the error position is now rarely 0)

**Pull request closed without merging**
